name: Noice
permissions:
  id-token: write
  contents: read
  checks: write
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build gradle project
        run: ./gradlew build
      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/debug/
